System.ArgumentOutOfRangeException.prototype.$ctor$1 = function(paramName) {
	System.ArgumentException.prototype.$ctor$3.call(this, System.ArgumentOutOfRangeException.RangeMessage, paramName);
	return this;
};
